---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - vim
        - zsh
          #        - pygmentize
        #this one is needed for dconf further down, must happen before wallpaper step
        - python3-psutil

# Wall paper example from LearnLinuxTV
#  - name: copy wallpaper file
#    copy:
#      src: files/desktop_images/ansible_test_desktop.jpg
#      dest: /usr/share/backgrounds/ansible_test_desktop.jpg
#      owner: root
#      group: root

#  - name: set wallpaper
#    become_user: greent
#    dconf:
#      key: "/org/gnome/desktop/background/picture-uri"
#      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

#  - name: set wallpaper position
#    become_user: greent
#    dconf:
#      key: "/org/gnome/desktop/background/picture-uri"
#      value: "'zoom'

          #- name: copy .zshrc file
          #copy:
          #src: files/dotConfig/zshrc
          #dest: /home/greent/.zshrc
          #owner: greent
          #group: greent

  - name: copy .vimrc
    copy:
      src: files/dotConfig/vimrc/
      dest: /home/greent/.vimrc
      owner: greent
      group: greent      
