---
- hosts: localhost
  connection: local
  become: true

# this should run apt update
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml


