---
- hosts: localhost
  connection: local
  become: true

# this should run apt update
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
#    - include: tasks/users.yml
    - include: tasks/packages.yml
#    - include: tasks/cron_Auto.yml


#  copy:
#    - include: tasks/dotConfig.yml

