---
- hosts: localhost
  connection: local
  become: true

# this should run apt update
  pre_tasks:
    - name: update (Debian Based Systems)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: False
      when: ansible_distribution in["Ubuntu", "Debian", "Pop!_OS"]

    - name: update (MacOSX)
      tags: always
      become: false
      community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes
      changed_when: False
      when: ansible_distribution == "MacOSX"

    
  tasks:
###    - include: tasks/users.yml
#    - include: tasks/packages.yml
#    - include: tasks/dotConfig.yml
###    - include: tasks/cron_Auto.yml
###    - include: tasks/desketopConf.yml	# work from around 50:00 learnlinuxtv 'using ansible to automate your laptop and desktop configs!'

