---
- hosts: localhost
  connection: local
  become: true

# this should run apt update
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron_Auto.yml
#    - include: tasks/desketopConf.yml	# work from around 50:00 learnlinuxtv 'using ansible to automate your laptop and desktop configs!'

#  copy:
#    - include: tasks/dotConfig.yml

