---
- name: Linux Packages (all system types)
  apt:
    name:
      - htop
      - tmux
      - vim
      - lynis
#     - docker.io

- name: Install Packages (Workstations)
  apt:
    name:
      # enviroment
      - zsh
      - powerlevel10k
      - python3-psutil      # needed for dconf, before wallpaper step
      # tools
      - nmap
      - git
      - ansible
      - neofetch
      - caffeine
      # fun ones.
      - lolcat
      - cowsay
    when: Workstations


- hosts: MacOSX
  tasks:
  - name: install Mac packages w/ homebrew
    package:
      name:
        # enviroment
        - zsh
        - powerlevel10k
        - python3-psutil      # needed for dconf, before wallpaper step
        # tools
        - tmux
        - vim
        - lynis
        - htop
        - nmap
        - syncthing
        - pygmentize          # color output for 'cat' (Mac only?)
        # fun ones
        - lolcat
        - cowsay
      state: present
      update_homebrew: yes
      upgrade_all: yes
#    when: ansible_distribution == "MacOSX"


#- name: Install Packages (netPi)
#  apt:
#    name:
#      - docker.io
#    when: netPi


#syncthing

# Mac Homebrew install
# Nerd fonts
#  $ brew tap homebrew/cask-fonts
#  $ brew install --cask font-hack-nerd-font


