---
# Setup automatic system updates though an ansible managed cron job.

#   -o means it will not update unless there have been changes to save on system resorces
#   addapted from learnlinuxtv https://www.learnlinux.tv/using-ansible-to-configure-your-desktops-and-laptops/

  - name: add ansible user
   user:
      name: ansible_Auto
      system: yes

  - name: setup sudo for ansible user
    copy:
      src: files/sudoer_ansible_Auto
      dest: /etc/sudoers.d/ansible_Auto
      owner: root
      group: root
      mode: 0440

#  - name: add ansible-pull cron job
#    cron:
#      name: ansible auto-provision
#      user: ansible_Auto
#      minute: "*/10"
#      job: ansible-pull -o -U https://github.com/GranitePlayground/ansible.SystemConfig.git 


